steps:
# Build image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/letsfooldocker:${COMMIT_SHA}', '.']
# Push image to artefact registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/letsfooldocker:${COMMIT_SHA}']
# Deploy to cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'letsfooldocker',
    '--image', 'gcr.io/${PROJECT_ID}/letsfooldocker:${COMMIT_SHA}',
    '--region', 'europe-west1',
    '--platform', 'managed'
  ]

images:
- 'gcr.io/${PROJECT_ID}/letsfooldocker:${COMMIT_SHA}'
options:
  logging: CLOUD_LOGGING_ONLY
